config/routes.rb
Rails.application.routes.draw do
  get 'partners/new'
  get 'partners/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/auth/:provider/callback', to: 'sessions#create'

  get '/tagged', to: "ingredients#tagged", as: :tagged

  root to: 'pages#home'
  get '/docs', to: 'pages#docs'
  get '/first' => 'pages#first'
  get '/sendtous' => 'pages#sendtous'
  get '/responsible' => 'pages#responsible'
  get '/responsibleingredient' => 'pages#responsibleingredient'
  get '/thanks' => 'produtos#thanks'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resources :items do
    resources :wishlists, except: :index
    resources :reviews
    resources :coupons
    end
  resources :wishlists, only: [:index]
  resources :requested_items
  resources :requested_ingredients
  resources :solicitacao_ingredientes
  resources :produtos
  resources :ingredients
  resources :combination
  resources :merger
  resources :partners, only: [:new, :create]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      post 'create_tracker', to: 'coupon_leads#create_coupon'
    end
   end

end

app/views/shared/_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-171153227-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-171153227-1');
</script>

app/views/shared/_flashes.html.erb
<style>
  .customize{
    min-width: 350px !important;
    background-color: #33D89E;
    font-size: 14px;
    color: white;
    font-weight: bold;
    font-family: 'Montserrat', sans-serif;
  }
  .customizealert{
    min-width: 350px !important;
    background-color: #BE0B0B;
    font-size: 14px;
    color: white;
    font-weight: bold;
    font-family: 'Montserrat', sans-serif;
  }
</style>
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1 customize" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1 customizealert" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
  <div class="d-flex justify-content-end">
  <% if user_signed_in? %>
  <div class="dropdown mr-4 mt-1">
  <%= image_tag "menunavbar.svg" %>
  <div class="dropdown-content">
    <figure class="d-flex align-items-center mt-3">
      <%= image_tag "usuario.svg", class:'userlog' %><figcaption class="ml-2 mt-1"> <%= current_user.email %></figcaption>
    </figure>
    <li>
      <%= link_to root_path, class:"dropdown-item fontnav" do %>
      <figure class="d-flex align-items-center mt-3">
        <%= image_tag "inicio.png" %><figcaption class="ml-2 mt-1"> Início</figcaption>
      </figure>
      <% end %>
      <p class="line"></p>

      <%= link_to ingredients_path, class:"dropdown-item fontnav" do %>
      <figure class="d-flex align-items-center mt-3">
        <%= image_tag "lupa2.png" %><figcaption class="ml-2 mt-1"> Buscar por ingrediente</figcaption>
      </figure>
      <% end %>
      <p class="line"></p>

      <%= link_to solicitacao_ingredientes_path, class:"dropdown-item fontnav" do %>
      <figure class="d-flex align-items-center mt-3">
        <%= image_tag "avaliaçãobranco.svg" %><figcaption class="ml-2 mt-1"> Sugerir avaliação de um ingrediente </figcaption>
      </figure>
      <% end %>
      <p class="line"></p>

      <%= link_to responsibleingredient_path, class:"dropdown-item fontnav" do %>
      <figure class="d-flex align-items-center mt-3">
        <%= image_tag "responsa.svg" %><figcaption class="ml-2 mt-1"> Responsabilidade limpp</figcaption>
      </figure>
      <% end %>
      <p class="line"></p>
      <%= link_to destroy_user_session_path, method: :delete, class:"dropdown-item fontnav" do %>
      <figure class="d-flex align-items-center mt-3">
        <%= image_tag "logout.png" %><figcaption class="ml-2 mt-1"> Log out</figcaption>
      </figure>
      <% end %>
      <p class="line"></p>
    </li>
  </div>
  </div>
  <% end %>
  </div>

app/views/shared/oldnavbar.html.erb
 <div class="d-flex justify-content-end">
  <% if user_signed_in? %>
  <div class="dropdown mr-4 mt-1">
  <%= image_tag "menunavbar.svg" %>
  <div class="dropdown-content">
    <figure class="d-flex align-items-center mt-3">
      <%= image_tag "usuario.svg", class:'userlog' %><figcaption class="ml-2 mt-1"> <%= current_user.email %></figcaption>
    </figure>
    <li>
      <%= link_to root_path, class:"dropdown-item fontnav" do %>
      <figure class="d-flex align-items-center mt-3">
        <%= image_tag "inicio.png" %><figcaption class="ml-2 mt-1"> Início</figcaption>
      </figure>
      <% end %>
      <p class="line"></p>

      <%= link_to ingredients_path, class:"dropdown-item fontnav" do %>
      <figure class="d-flex align-items-center mt-3">
        <%= image_tag "lupa2.png" %><figcaption class="ml-2 mt-1"> Buscar por ingrediente</figcaption>
      </figure>
      <% end %>
      <p class="line"></p>

      <%= link_to solicitacao_ingredientes_path, class:"dropdown-item fontnav" do %>
      <figure class="d-flex align-items-center mt-3">
        <%= image_tag "avaliaçãobranco.svg" %><figcaption class="ml-2 mt-1"> Sugerir avaliação de um ingrediente </figcaption>
      </figure>
      <% end %>
      <p class="line"></p>

      <%= link_to responsibleingredient_path, class:"dropdown-item fontnav" do %>
      <figure class="d-flex align-items-center mt-3">
        <%= image_tag "responsa.svg" %><figcaption class="ml-2 mt-1"> Responsabilidade limpp</figcaption>
      </figure>
      <% end %>
      <p class="line"></p>
      <%= link_to destroy_user_session_path, method: :delete, class:"dropdown-item fontnav" do %>
      <figure class="d-flex align-items-center mt-3">
        <%= image_tag "logout.png" %><figcaption class="ml-2 mt-1"> Log out</figcaption>
      </figure>
      <% end %>
      <p class="line"></p>
    </li>
  </div>
  </div>
  <% end %>
  </div>