config/routes.rb
Rails.application.routes.draw do
  get 'partners/new'
  get 'partners/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/auth/:provider/callback', to: 'sessions#create'

  get '/tagged', to: "ingredients#tagged", as: :tagged

  root to: 'pages#home'
  get '/docs', to: 'pages#docs'
  get '/first' => 'pages#first'
  get '/sendtous' => 'pages#sendtous'
  get '/responsible' => 'pages#responsible'
  get '/responsibleingredient' => 'pages#responsibleingredient'
  get '/thanks' => 'produtos#thanks'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resources :items do
    resources :wishlists, except: :index
    resources :reviews
    resources :coupons
    end
  resources :wishlists, only: [:index]
  resources :requested_items
  resources :requested_ingredients
  resources :solicitacao_ingredientes
  resources :produtos
  resources :ingredients
  resources :combination
  resources :merger
  resources :partners, only: [:new, :create]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      post 'create_tracker', to: 'coupon_leads#create_coupon'
    end
   end

end

app/models/requested_item.rb
class RequestedItem < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
end

app/controllers/requested_items_controller.rb
class RequestedItemsController < ApplicationController
  before_action :set_requested_item, only: [:show, :edit, :update, :destroy]
  def new
    @requested_item = RequestedItem.new
    authorize @requested_item
  end

  def create
    @requested_item = RequestedItem.new(requested_item_params)
    authorize @requested_item
    @requested_item.user = current_user
    if @requested_item.save
      redirect_to sendtous_path
    else
      render :new
    end
  end

  def index
    @requested_items = policy_scope(RequestedItem)
  end

  def show
  end

  private

  def set_requested_item
    @requested_item = RequestedItem.find(params[:id])
    authorize @requested_item
  end

  def requested_item_params
    params.require(:requested_item).permit(:email, photos: [])
  end
end

app/views/requested_items/_form.html.erb
<style>
    .simple_form label{
      color: white;
    }
    .upload-btn-wrapper {
      position: relative;
      overflow: hidden;
    }

    .btn {
      border: 2px solid #8F89DD;
      color: #8F89DD;
      font-family: 'Montserrat', sans-serif;
      background-color: white;
      padding: 4px 10px;
      border-radius: 15px;
      font-size: 13px;
      font-weight: bold;
    }

    .upload-btn-wrapper input[type=file] {
      font-size: 100px;
      position: absolute;
      left: 0;
      top: 0;
      opacity: 0;
    }
    .confirm{
      font-family: 'Montserrat', sans-serif;
      font-size: 13px;
      margin-bottom: -10px;
      margin-left: 10px;
    }
    .btn-envio{
      color: white;
      background-color: #8F89DD;
      border-radius: 30px;
      padding: 0.5rem 2rem;
      font-weight: bold;
      font-family: 'Montserrat', sans-serif;
      font-size: 13px;
      box-shadow: 0px 2px 2px #33313261;
      margin-top: -30px;
    }
</style>
<div class="p-4">
  <p class="confirm">Confirme seu e-mail (*campo obrigatório)</p>
<%= simple_form_for @requested_item do |f| %>
        <%= f.input :email,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "email", class: 'rounded-pill' } %>
        <div class="upload-btn-wrapper">
        <button class="btn mt-1">Escolha as fotos aqui</button>
        <input type="file" name="myfile" />
        <%= f.input :photos, as: :file, input_html: { multiple: true }, label: "." %>
        </div>
        <%= f.button :submit, "Enviar", class:"btn btn-envio" %>
      <% end %>
</div>

app/views/requested_items/index.html.erb
<style>
  h4{
    color: #333132;
    font-weight: bold;
    font-family: 'Montserrat', sans-serif;
    }
  .evaluation{
    color: #707070;
    font-family: 'Montserrat', sans-serif;
    font-size: 14px;
    }
    .btn-avaliacao{
      color: white;
      background-color: #8F89DD;
      border-radius: 30px;
      padding: 0.5rem 2rem;
      font-weight: bold;
      font-family: 'Montserrat', sans-serif;
      font-size: 13px;
      box-shadow: 0px 2px 2px #33313261;
    }
</style>
<div class="container-fluid mt-4">
  <div class="d-flex justify-content-center"><%= image_tag "barcode.svg" %></div>
    <h5 class="text-center mt-5">Não encontrou um produto e gostaria que ele fosse avaliado?</h5>
    <p class="text-center mt-5 evaluation">Para sugerir a avaliação, clique no botão abaixo e envie as fotos do rótulo para nossa equipe.</p>
    <div class="d-flex justify-content-center">
    <% if policy(RequestedItem).create? %>
        <%= link_to "Sugerir avaliação", new_requested_item_path, class: "btn btn-avaliacao mt-4"%>
    <% end %>
    </div>
</div>

app/views/requested_items/new.html.erb
<style>
  h4{
    color: #333132;
    font-weight: bold;
    font-family: 'Montserrat', sans-serif;
    }
  p{
    color: #707070;
    font-family: 'Montserrat', sans-serif;
    }
    .btn-avaliacao{
      color: white;
      background-color: #8F89DD;
      border-radius: 30px;
      padding: 0.5rem 2rem;
      font-weight: bold;
      font-family: 'Montserrat', sans-serif;
      font-size: 13px;
      box-shadow: 0px 2px 2px #33313261;
    }
</style>
<div class="container-fluid mt-4">
  <div class="d-flex justify-content-center"><%= image_tag "sendtous.svg" %></div>
    <h4 class="text-center mt-5">Envie o rótulo para gente!</h4>
    <p class="text-center mt-4">As fotos devem estar visíveis e serem de rótulos de verdade, de produtos industrializados de cosméticos e higiene pessoal.</p>
    <%= render 'form', requested_item: @requested_item %>
</div>