config/routes.rb
Rails.application.routes.draw do
  get 'partners/new'
  get 'partners/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/auth/:provider/callback', to: 'sessions#create'

  get '/tagged', to: "ingredients#tagged", as: :tagged

  root to: 'pages#home'
  get '/docs', to: 'pages#docs'
  get '/first' => 'pages#first'
  get '/sendtous' => 'pages#sendtous'
  get '/responsible' => 'pages#responsible'
  get '/responsibleingredient' => 'pages#responsibleingredient'
  get '/thanks' => 'produtos#thanks'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resources :items do
    resources :wishlists, except: :index
    resources :reviews
    resources :coupons
    end
  resources :wishlists, only: [:index]
  resources :requested_items
  resources :requested_ingredients
  resources :solicitacao_ingredientes
  resources :produtos
  resources :ingredients
  resources :combination
  resources :merger
  resources :partners, only: [:new, :create]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      post 'create_tracker', to: 'coupon_leads#create_coupon'
    end
   end

end

app/models/solicitacao_ingrediente.rb
class SolicitacaoIngrediente < ApplicationRecord
end

app/controllers/solicitacao_ingredientes_controller.rb
class SolicitacaoIngredientesController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_solicitacao_ingrediente, only: [:show, :edit, :update, :destroy]
  def new
    @solicitacao_ingrediente = SolicitacaoIngrediente.new
    authorize @solicitacao_ingrediente
  end

  def create
    @solicitacao_ingrediente = SolicitacaoIngrediente.new(solicitacao_ingrediente_params)
    authorize @solicitacao_ingrediente
    if @solicitacao_ingrediente.save
      redirect_to sendtous_path
    else
      render :new
    end
  end

  def index
    @solicitacao_ingredientes = policy_scope(SolicitacaoIngrediente)
  end

  def show
  end

  private

  def set_solicitacao_ingrediente
    @solicitacao_ingrediente = SolicitacaoIngrediente.find(params[:id])
    authorize @solicitacao_ingrediente
  end

  def solicitacao_ingrediente_params
    params.require(:solicitacao_ingrediente).permit(:email, :ingrediente, :obs)
  end
end

app/views/solicitacao_ingredientes/_form.html.erb
<style>
    .simple_form label{
      font-family: 'Montserrat', sans-serif;
      font-size: 13px;
      margin-bottom: -10px;
      margin-left: 10px;
      color: #707070;
    }

    .btn {
      border: 2px solid #8F89DD;
      color: #8F89DD;
      font-family: 'Montserrat', sans-serif;
      background-color: white;
      padding: 4px 10px;
      border-radius: 15px;
      font-size: 13px;
      font-weight: bold;
    }

    .upload-btn-wrapper input[type=file] {
      font-size: 100px;
      position: absolute;
      left: 0;
      top: 0;
      opacity: 0;
    }
    .confirm{
      font-family: 'Montserrat', sans-serif;
      font-size: 13px;
      margin-bottom: -10px;
      margin-left: 10px;
    }
    .btn-envio{
      color: white;
      background-color: #8F89DD;
      border-radius: 30px;
      padding: 0.5rem 2rem;
      font-weight: bold;
      font-family: 'Montserrat', sans-serif;
      font-size: 13px;
      box-shadow: 0px 2px 2px #33313261;
    }
</style>
<div class="p-4 d-flex justify-content-center">
<%= simple_form_for @solicitacao_ingrediente do |f| %>
        <%= f.input :email,
                  required: true,
                  label: "Seu e-mail (campo obrigatório)",
                  autofocus: true,
                  input_html: { autocomplete: "email", class: 'rounded-pill sizeformdesk' } %>
        <%= f.input :ingrediente,
                  required: true,
                  label: "Nome do Ingrediente conforme escrito na embalagem (campo obrigatório)",
                  autofocus: true,
                  input_html: { class: 'rounded-pill sizeformdesk' } %>
        <%= f.input :obs,
                  label: "Gostaria de adicionar algum comentário?",
                  autofocus: true,
                  input_html: { class: 'rounded-pill sizeformdesk' } %>
        <%= f.button :submit, "Enviar", class:"btn btn-envio" %>
      <% end %>
</div>

app/views/solicitacao_ingredientes/index.html.erb
<style>
  h4{
    color: #333132;
    font-weight: bold;
    font-family: 'Montserrat', sans-serif;
    }
     h5{
    color: #333132;
    font-weight: bold;
    font-family: 'Montserrat', sans-serif;
    }
  .evaluation{
    color: #707070;
    font-family: 'Montserrat', sans-serif;
    font-size: 14px;
    }
    .btn-avaliacao{
      color: white;
      background-color: #8F89DD;
      border-radius: 30px;
      padding: 0.5rem 2rem;
      font-weight: bold;
      font-family: 'Montserrat', sans-serif;
      font-size: 13px;
      box-shadow: 0px 2px 2px #33313261;
    }
</style>
<div class="container-fluid mt-4">
  <div class="d-flex justify-content-center"><%= image_tag "ingredientred.svg", class:"sizeingredientimage" %></div>
    <h5 class="text-center mt-5 sizenewingredient">Não encontrou um ingrediente e gostaria que ele seja avaliado?</h5>
    <p class="text-center mt-5 evaluation">Para sugerir a avaliação, clique no botão abaixo e nos envie as informações necessárias de ingredientes de produtos de higiene pessoal e cosmética.</p>
    <div class="d-flex justify-content-center">
    <% if policy(SolicitacaoIngrediente).create? %>
        <%= link_to "Sugerir avaliação", new_solicitacao_ingrediente_path, class: "btn btn-avaliacao mt-4"%>
    <% end %>
    </div>
</div>

app/views/solicitacao_ingredientes/new.html.erb
<style>
  h4{
    color: #333132;
    font-weight: bold;
    font-family: 'Montserrat', sans-serif;
    }
  p{
    color: #707070;
    font-family: 'Montserrat', sans-serif;
    }
    .btn-avaliacao{
      color: white;
      background-color: #8F89DD;
      border-radius: 30px;
      padding: 0.5rem 2rem;
      font-weight: bold;
      font-family: 'Montserrat', sans-serif;
      font-size: 13px;
      box-shadow: 0px 2px 2px #33313261;
    }
</style>
<div class="container-fluid mt-4">
  <div class="d-flex justify-content-center"><%= image_tag "sendtous.svg" %></div>
    <h4 class="text-center mt-5">Qual ingrediente você gostaria que seja avaliado?</h4>
    <p class="text-center mt-4">O nome deve estar conforme escrito na embalagem do produto.</p>
    <%= render 'form', solicitacao_ingrediente: @solicitacao_ingrediente %>
</div>