config/routes.rb
Rails.application.routes.draw do
  get 'partners/new'
  get 'partners/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/auth/:provider/callback', to: 'sessions#create'

  get '/tagged', to: "ingredients#tagged", as: :tagged

  root to: 'pages#home'
  get '/docs', to: 'pages#docs'
  get '/first' => 'pages#first'
  get '/sendtous' => 'pages#sendtous'
  get '/responsible' => 'pages#responsible'
  get '/responsibleingredient' => 'pages#responsibleingredient'
  get '/thanks' => 'produtos#thanks'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resources :items do
    resources :wishlists, except: :index
    resources :reviews
    resources :coupons
    end
  resources :wishlists, only: [:index]
  resources :requested_items
  resources :requested_ingredients
  resources :solicitacao_ingredientes
  resources :produtos
  resources :ingredients
  resources :combination
  resources :merger
  resources :partners, only: [:new, :create]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      post 'create_tracker', to: 'coupon_leads#create_coupon'
    end
   end

end

app/models/item.rb
class Item < ApplicationRecord

  acts_as_taggable_on :category
  acts_as_taggable_on :subcategory
  acts_as_taggable_on :toxicity

  has_many :wishlists, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :coupons, dependent: :destroy
  has_many :combinations, dependent: :destroy
  has_many :ingredients, through: :combinations
  has_one_attached :photo
  has_many_attached :certification_photos

  include PgSearch::Model
  multisearchable against: [:name]
  pg_search_scope :search_by_name_and_ingredient,
    against: [ :name ],
    associated_against: {
    category: [:name],
    subcategory: [:name],
    toxicity: [:name],
    ingredients: [:name],
    ingredients: [:other_names]
  },
    using: {
      tsearch: { prefix: true }
    }

    $category = ['Cabelos', 'Higiene Pessoal', 'Cuidados com a pele', 'Maquiagem']
    $subcategory = ['Shampoos', 'Tratamentos Capilares', 'Finalizadores Capilares', 'Tinturas', 'Desodorantes', 'Higiene Bucal', 'Limpeza Facial', 'Limpeza Corporal', 'Tratamento Facial', 'Tratamento Corporal', 'Protetor Solar', 'Maquiagem Pele', 'Maquiagem Olhos', 'Maquiagem Lábios' ]
    $toxicity = ['Não contém ingredientes suspeitos', 'Vegano', 'Grávidas deveriam evitar', 'Contém glúten', 'Não alergênico']

    def calculate_average
      return 0 unless reviews.any?
      reviews.average(:rating).to_i
    end

    def count_certification_photo
      certification_photos.count
    end

    def toxicity_classifier
      rated = 0
      self.ingredients.each do |ingredient|
        rated += 10 if ingredient.risk_to_health == "red"
        rated += 8 if ingredient.risk_to_health == "orange"
        rated += 5 if ingredient.risk_to_health == "yellow"
        rated += 2 if ingredient.risk_to_health == "grey"
        rated += 10 if ingredient.risk_to_enviroment == "red"
        rated += 8 if ingredient.risk_to_enviroment == "orange"
        rated += 5 if ingredient.risk_to_enviroment == "yellow"
        rated += 2 if ingredient.risk_to_enviroment == "grey"
        rated += 2 if ingredient.allergenic == "sim"

      end
      self.update(toxicity_rate: rated)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  def new
    @item = Item.new
    authorize @item
  end

  def create
    @item = Item.new(item_params)
    authorize @item

    if @item.save
      redirect_to items_path
    else
      render :new
    end

  end

  def index
    @wishlist = Wishlist.new
    @review = Review.new
    @user_wishlists = Item.where(id: current_user.wishlists.pluck(:item_id))
    if params[:query].present?
      @items = policy_scope(Item).search_by_name_and_ingredient(params[:query])
    elsif params[:search].present?
      @filter = params["search"]["category"].concat(params["search"]["subcategory"]).concat(params["search"]["toxicity"]).flatten.reject(&:blank?)
      @items = policy_scope(Item).order(toxicity_rate: :asc).search_by_name_and_ingredient("#{@filter}")
    elsif case params[:order]
          when 'average'
            @items = policy_scope(Item).order(toxicity_rate: :desc).sort_by(&:calculate_average).reverse!
          when 'cleanest'
          # @items = policy_scope(Item).left_outer_joins(:combinations).group('items.id').order('count(combinations.*) asc')
          @items = policy_scope(Item).order(toxicity_rate: :asc)
          when 'coupons'
          @items = policy_scope(Item).left_outer_joins(:coupons).group('items.id').order('count(coupons.*) desc')
          when 'certifications'
            @items = policy_scope(Item).order(toxicity_rate: :desc).sort_by(&:count_certification_photo).reverse!
          end
    else
      @items = policy_scope(Item).order(toxicity_rate: :asc)
    end
  end

  def show
    @wishlist = Wishlist.new
    @user_wishlists = Item.where(id: current_user.wishlists.pluck(:item_id))
    @coupon = Coupon.new
    @reviews = @item.reviews
    @review = Review.new
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      render :edit
  end
  end

  def destroy
    @item.destroy
    redirect_to items_path
  end


  private

  def set_item
    @item = Item.find(params[:id])
    authorize @item
  end

  def item_params
    params.require(:item).permit(:name, :ingredient, :photo, :tag, :average, :category, :subcategory, :toxicity, :order, certification_photos: [])
  end
end

app/views/items/_cardindex.html.erb
<div class="row justify-content-center">
  <div class="column d-flex flex-wrap">
     <% @items.each do |item| %>
     <div class="card shadow-sm bg-white mt-3 ml-3" style="width: 20rem; border-radius: 8px; ">
       <div class="card-body d-flex justify-content-start">
         <div class="d-flex align-items-end position">
         <% if item.photo.attached? %>
          <%= cl_image_tag item.photo.key, width: 85, height: 85, crop: :pad, class:"shadowcss bg-white rounded" %>
         <% else %>
          <img src="https://images.unsplash.com/photo-1503236823255-94609f598e71?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" class="card-photo"/>
         <% end %>
         <% if item.reviews.empty? %>
            <p class="card-text font notavailable"><%= "Não avaliado ainda" %></p>
          <% else %>
            <% item.calculate_average.times do %>
              <i class="fas fa-star star"></i>
            <% end %>
          <% end %>
         </div>
         <p class="card-text font case"><%= item.name %></p>
         <div class="d-flex justify-content-end space">
          <% if item.coupons.exists? %>
          <%= link_to item_coupons_path(item) do %>
            <%= image_tag "desconto2.png", class:"desconto mt-2" %>
          <% end %>
          <% end %>
          <%= link_to item_wishlists_path(item), method: :post do %>
            <div class="<%= @user_wishlists.include?(item) ? "btn-purpleheart" : "btn-greyheart" %>">
              <i class="fas fa-heart"></i>
            </div>
          <% end %>
         </div>
        <div class="d-flex justify-content-end">
        <%= link_to item_path(item), class:"component" do %>
          <%= image_tag "Componente.svg" %>
        <% end %>
        </div>
       </div>
     </div>
     <% end %>
</div>

app/views/items/_carditemingredient.html.erb
<style>
  .carditemingredient{
    border: none !important;
  }
</style>
    <ul class="marginul">
        <% @item.combinations.each do |combination| %>
        <div class="card carditemingredient" style="width: 20rem; ">
          <div class="card-body d-flex justify-content-start">
          <% if combination.ingredient.name == "PARFUM" %>
            <li class="mt-1 mb-2 ingredientlink"><%= combination.ingredient.name %><%= image_tag "alert.svg", class:"alertsize" %></li>
        <% else %>
            <li class="mt-1 mb-2 ingredientlink"><%= combination.ingredient.name %></li>
        <% end %>

        <div>
        <%= image_tag "saude.svg", class:"marginhealth2" %>
        <% if combination.ingredient.risk_to_health == "yellow" %>
        <span class="dotyellow2"></span>
        <% elsif combination.ingredient.risk_to_health == "red"  %>
        <span class="dotred2"></span>
        <% elsif combination.ingredient.risk_to_health == "grey"  %>
        <span class="dotgrey2"></span>
        <% elsif combination.ingredient.risk_to_health == "orange"  %>
        <span class="dotorange2"></span>
        <% else %>
        <span class="dotgreen2"></span>
        <% end %>
        </div>
        <div>
        <%= image_tag "ambiente.svg", class:"marginenvironment" %>
        <% if combination.ingredient.risk_to_enviroment == "yellow" %>
        <span class="dotyellow2"></span>
        <% elsif combination.ingredient.risk_to_enviroment == "red"  %>
        <span class="dotred2"></span>
        <% elsif combination.ingredient.risk_to_enviroment == "orange"  %>
        <span class="dotorange2"></span>
        <% elsif combination.ingredient.risk_to_enviroment == "grey"  %>
        <span class="dotgrey2"></span>
        <% else %>
        <span class="dotgreen2"></span>
        <% end %>
        </div>
        <div>
        <%= image_tag "alergia.svg", class:"marginhealth2" %>
          <% if combination.ingredient.allergenic == "sim" %>
          <p class="potencialsim2">SIM</p>
          <% else %>
          <p class="potencialnao2">NÃO</p>
          <% end %>
        </div>
        <%= link_to ingredient_path(combination.ingredient), class:"componentshow" do %>
          <%= image_tag "Componente.svg" %>
        <% end %>
        </div>
        <p class="linea">_____________________________________________</p>
        <% end %>
        </div>
        </ul>
        <% if @item.obs.blank? %>
        <% else %>
        <p class="card-text itemobs">*<%= @item.obs %></p>
        <% end %>

app/views/items/_cardshow.html.erb
<style>
  .cardshow{
    background-color: #F2F2F2 !important;
    border: none !important;
  }
</style>
<div class="card cardshow mt-3 ml-1" style="width: 20rem; border-radius: 8px; ">
     <div class="card-body d-flex justify-content-start">
       <% if @item.photo.attached? %>
        <%= cl_image_tag @item.photo.key, width: 80, height: 80, crop: :pad, class:"shadowcss bg-white rounded" %>
       <% else %>
        <img src="https://images.unsplash.com/photo-1503236823255-94609f598e71?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" class="card-photo"/>
       <% end %>
       <p class="card-text showname"><%= @item.name %></p>
       <% if @item.reviews.empty? %>
          <p class="card-text naoavaliadoshow"><%= "Não avaliado ainda" %></p>
          <% else %>
          <% @item.calculate_average.times do %>
            <i class="fas fa-star starshow"></i>
          <% end %>
       <% end %>
       </div>
       <div class="d-flex justify-content-end spaceshow">
          <% if @item.coupons.exists? %>
          <%= link_to item_coupons_path(@item) do %>
            <%= image_tag "desconto2.png", class:"desconto mt-2" %>
          <% end %>
          <% end %>
          <%= link_to item_wishlists_path(@item), method: :post do %>
            <div class="<%= @user_wishlists.include?(@item) ? "btn-purpleheart" : "btn-greyheart" %>">
              <i class="fas fa-heart"></i>
            </div>
          <% end %>
       </div>
     </div>
</div>

app/views/items/_sponsoreditems.html.erb
<div class="row justify-content-center">
  <div class="column d-flex flex-wrap">
     <% @sponsoreditem1 = Item.find(11) %>
     <div class="card shadow-sm bg-white mt-3 ml-3" style="width: 20rem; border-radius: 8px; ">
       <div class="card-body d-flex justify-content-start">
         <div><i class="far fa-check-circle sponsored"></i></div>
         <div class="d-flex align-items-end position">
         <% if @sponsoreditem1.photo.attached? %>
          <%= cl_image_tag @sponsoreditem1.photo.key, width: 85, height: 85, crop: :pad, class:"shadowcss bg-white rounded" %>
         <% else %>
          <img src="https://images.unsplash.com/photo-1502977249166-824b3a8a4d6d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=80" class="card-photo"/>
         <% end %>
         <% if @sponsoreditem1.reviews.empty? %>
            <p class="card-text font notavailable"><%= "Não avaliado ainda" %></p>
          <% else %>
            <% @sponsoreditem1.calculate_average.times do %>
              <i class="fas fa-star star"></i>
            <% end %>
          <% end %>
         </div>
         <p class="card-text font case"><%= @sponsoreditem1.name %></p>
         <div class="d-flex justify-content-end space">
          <% if @sponsoreditem1.coupons.exists? %>
          <%= link_to item_coupons_path(@sponsoreditem1) do %>
            <%= image_tag "desconto2.png", class:"desconto mt-2" %>
          <% end %>
          <% end %>
          <%= link_to item_wishlists_path(@sponsoreditem1), method: :post do %>
            <div class="<%= @user_wishlists.include?(@sponsoreditem1) ? "btn-purpleheart" : "btn-greyheart" %>">
              <i class="fas fa-heart"></i>
            </div>
          <% end %>
         </div>
        <div class="d-flex justify-content-end">
        <%= link_to item_path(@sponsoreditem1), class:"component" do %>
          <%= image_tag "Componente.svg" %>
        <% end %>
        </div>
       </div>
     </div>
</div>
<div class="row justify-content-center">
    <div class="column d-flex flex-wrap">
     <% @sponsoreditem2 = Item.find(12) %>
     <div class="card shadow-sm bg-white mt-3 ml-3" style="width: 20rem; border-radius: 8px; ">
       <div class="card-body d-flex justify-content-start">
         <div class="d-flex align-items-end position">
         <% if @sponsoreditem2.photo.attached? %>
          <%= cl_image_tag @sponsoreditem2.photo.key, width: 85, height: 85, crop: :pad, class:"shadowcss bg-white rounded" %>
         <% else %>
          <img src="https://images.unsplash.com/photo-1503236823255-94609f598e71?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" class="card-photo"/>
         <% end %>
         <% if @sponsoreditem2.reviews.empty? %>
            <p class="card-text font notavailable"><%= "Não avaliado ainda" %></p>
          <% else %>
            <% @sponsoreditem2.calculate_average.times do %>
              <i class="fas fa-star star"></i>
            <% end %>
          <% end %>
         </div>
         <p class="card-text font case"><%= @sponsoreditem2.name %></p>
         <i class="far fa-check-circle sponsored"></i>
         <div class="d-flex justify-content-end space">
          <% if @sponsoreditem2.coupons.exists? %>
          <%= link_to item_coupons_path(@sponsoreditem2) do %>
            <%= image_tag "desconto2.png", class:"desconto mt-2" %>
          <% end %>
          <% end %>
          <%= link_to item_wishlists_path(@sponsoreditem2), method: :post do %>
            <div class="<%= @user_wishlists.include?(@sponsoreditem2) ? "btn-purpleheart" : "btn-greyheart" %>">
              <i class="fas fa-heart"></i>
            </div>
          <% end %>
         </div>
        <div class="d-flex justify-content-end">
        <%= link_to item_path(@sponsoreditem2), class:"component" do %>
          <%= image_tag "Componente.svg" %>
        <% end %>
        </div>
       </div>
     </div>
</div>
<div class="row justify-content-center">
     <div class="column d-flex flex-wrap">
     <% @sponsoreditem3 = Item.find(13) %>
     <div class="card shadow-sm bg-white mt-3 ml-3" style="width: 20rem; border-radius: 8px; ">
       <div class="card-body d-flex justify-content-start">
         <div class="d-flex align-items-end position">
         <% if @sponsoreditem3.photo.attached? %>
          <%= cl_image_tag @sponsoreditem3.photo.key, width: 85, height: 85, crop: :pad, class:"shadowcss bg-white rounded" %>
         <% else %>
          <img src="https://images.unsplash.com/photo-1503236823255-94609f598e71?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" class="card-photo"/>
         <% end %>
         <% if @sponsoreditem3.reviews.empty? %>
            <p class="card-text font notavailable"><%= "Não avaliado ainda" %></p>
          <% else %>
            <% @sponsoreditem3.calculate_average.times do %>
              <i class="fas fa-star star"></i>
            <% end %>
          <% end %>
         </div>
         <p class="card-text font case"><%= @sponsoreditem3.name %></p>
         <i class="far fa-check-circle sponsored"></i>
         <div class="d-flex justify-content-end space">
          <% if @sponsoreditem3.coupons.exists? %>
          <%= link_to item_coupons_path(@sponsoreditem3) do %>
            <%= image_tag "desconto2.png", class:"desconto mt-2" %>
          <% end %>
          <% end %>
          <%= link_to item_wishlists_path(@sponsoreditem3), method: :post do %>
            <div class="<%= @user_wishlists.include?(@sponsoreditem3) ? "btn-purpleheart" : "btn-greyheart" %>">
              <i class="fas fa-heart"></i>
            </div>
          <% end %>
         </div>
        <div class="d-flex justify-content-end">
        <%= link_to item_path(@sponsoreditem3), class:"component" do %>
          <%= image_tag "Componente.svg" %>
        <% end %>
        </div>
       </div>
     </div>
</div>
</div>

app/views/items/new.html.erb
<style>
  h1{
      font-family: 'Quicksand', sans-serif;
      color: #707070;
      font-size: 30px;
    }
    .font2{
      color: #8F89DD;
    }
</style>
<div class="container mt-3">

  <div class="text-center mb-3">
    <h1 class="text-center">Você não é autorizado a adicionar um novo item</h1>
</div>

app/views/items/show.html.erb
<div class="mt-2">
  <style>
    body{
      background-color: #F2F2F2;
    }
    .btn-cadastrar{
      color: white;
      background-color: #333132;
      border-radius: 30px;
      padding: 0.3rem 1rem;
      font-weight: bold;
      font-family: 'Montserrat', sans-serif;
      font-size: 13px;
      box-shadow: 0px 2px 2px #33313261;
    }
    p{
    color: #707070;
    font-family: 'Montserrat', sans-serif;
    font-size: 14px;
    text-decoration: none;
    }
    .nav-link{
    display: block;
    padding: 0.5rem 0.5rem !important;
    }
    .active{
      background-color: white !important;
      border: none;
      border-radius: 8px;
      color: #333132 !important;
      font-family: 'Montserrat', sans-serif;
      font-weight: bold;
      font-size: 13px;
      padding: 20px;
    }
    .show {
      background: white !important;
      border: none;
      color: #333132 !important;
      font-family: 'Montserrat', sans-serif;

    }
    .nav-link{
      color: white;
      font-family: 'Montserrat', sans-serif;
    }
    .nav-item{
      background-image: linear-gradient(#66D8A0, #8D8BDB);
      color: #333132 !important;
      font-family: 'Montserrat', sans-serif;
      border-radius: 23px;
      border-color: white;
      font-weight: bold;
      font-size: 12px;
    }
    *,
    *::before,
    *::after {
       box-sizing: content-box;
    }
  </style>

  <div class="p-1">
  <%= render 'cardshow' %>
  <ul class="nav nav-pills mt-3" id="pills-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Ingredientes</a>
  </li>
  <li class="nav-item ml-1" role="presentation">
    <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Certificações</a>
  </li>
  <li class="nav-item ml-1" role="presentation">
    <a class="nav-link" id="pills-contact-tab" data-toggle="pill" href="#pills-contact" role="tab" aria-controls="pills-contact" aria-selected="false">Avaliações (<%= @item.reviews.count %>)</a>
  </li>
</ul>
<div class="tab-content" id="pills-tabContent">
  <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
  <div class="d-flex align-items-center">
    <div class="ingredientname">
  <% if @item.combinations.any? %>
        <%= render 'carditemingredient' %>
  <% else %>
        <p class="card-text ingredientname"><%= 'Esse item não contém ingredientes suspeitos avaliados pela limpp.' %></p>
        <p class="linea">________________________________________________</p>
  <% end %>


    <p class="fontdate mt-1">Item atualizado em <%= @item.updated_at %></p>
    <p class="fonttitle mt-5">Aspectos avaliados por nós:</p>
    <div class="d-flex">
    <%= image_tag "saude.svg", class:"marginhealth" %>
    <p class="marginrisk">Risco à saúde</p>
    </div>
    <div class="d-flex">
    <%= image_tag "ambiente.svg", class:"marginhealth" %>
    <p class="marginrisk">Risco ao meio ambiente</p>
    </div>
    <div class="d-flex">
    <%= image_tag "alergia.svg", class:"marginhealth" %>
    <p class="marginrisk">Potencial alergênico</p>
    </div>

<div class="d-flex"><p class="fonttitle mt-5">Critérios de avaliação</p><%= image_tag "limppsemslogan.svg" , class:"sizelogocriteria" %> </div>
<span class="bigdotgreen"></span>
    <p class="criterios"> Seguro em cosméticos </p>
    <p class="criterioscinza mr-5"> É seguro em cosméticos sem restrições de uso ou quantidade, e sem causar impactos à saúde e/ou ao meio ambiente.</p>
<span class="bigdotyellow"></span>
    <p class="criteriosyellow"> Seguro em cosméticos, com restrições  </p>
    <p class="criterioscinza mr-5"> É seguro em cosméticos com restrições de quantidade e/ou uso, segundo evidências científicas. E podem causar impactos à saúde e/ou ao meio ambiente se forem utilizadas em finalidades distintas as aprovadas ou em quantidade acima das permitidas.</p>
<span class="bigdotorange"></span>
    <p class="criteriosorange"> Classificados como seguros, mas ainda em avaliação </p>
    <p class="criterioscinza mr-5"> São considerados seguros em cosméticos por órgãos especializados, porém, estão com estudos ainda em avaliação de danos mais graves.</p>
<span class="bigdotred"></span>
    <p class="criteriosred"> Comprovadamente associados a danos graves </p>
    <p class="criterioscinza mr-5"> Já existe comprovação científica conclusiva que podem causar impactos graves à saúde e/ou ao meio ambiente.</p>
<span class="bigdotgrey"></span>
    <p class="criteriosgrey"> Potencial inconclusivo   </p>
    <p class="criterioscinza mr-5"> Estudos não permitem nenhuma conclusão por estarem em andamento ou obterem dados divergentes sobre sua segurança a saúde e/ou impactos ao meio ambiente.</p>
</div>
  </div>
    <div class="d-flex mt-5"><%= image_tag "limppsemslogan.svg" , class:"sizelogocolab mr-1" %><p class="fontcolab mt-4"> é uma plataforma colaborativa!</p></div>
    <p class="obs2 mb-2">Classificamos ingredientes em que as fotos dos produtos nos são enviadas por usuários da plataforma. Estamos abertos para correções/atualizações de fórmula por parte dos fabricantes. Mostramos apenas os ingredientes que são considerados suspeitos. As demais substâncias da fórmula ou são seguras tanto para saúde como meio ambiente e não são alergênicas, ou ainda não foram avaliadas por nossa equipe. Sente falta de algum? Fale conosco através do e-mail limpp.com.vc@gmail.com</p>
  </div>
  <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
     <% if @item.certification_photos.attached? %>
      <% @item.certification_photos.each do |photo| %>
       <%= cl_image_tag photo.key, width: 80, height: 80, crop: :pad, class:"shadowcss bg-white rounded mt-3" %>
       <% end %>
     <% else %>
        <p class="card-text ingredientname"><%= 'Esse item não tem certificados aprovados pela limpp.' %></p>
     <% end %>
     <p class="lineacertification mt-3">___________________________________________________</p>
      <div class="d-flex"><p class="fontnota mt-4">Nota da</p><%= image_tag "limppsemslogan.svg" , class:"sizelogonota mb-2" %> </div>
      <p class="mt-2 selosmarcas">Marcas que possuem selos oficiais que certificam que seus ingredientes são naturais, orgânicos, que não testam em animais e/ou que tem embalagem reciclável ganham pontos para nossa escolha.</p>
  </div>
<div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
    <% if @item.reviews.empty? %>
      <br><%=    link_to 'Seja o primeiro a avaliar esse produto', new_item_review_path(@item.id), class: "btn btn-cadastrar mt-3 mb-5" %>
    <% else %>
    <p class="marginaverage">Média geral</p>
    <p class="number"><%= @item.calculate_average %></p>

    <p class="font-weight-bold marginevaluation">de <%= @item.reviews.count %> <% if @item.reviews.count == 1 %> Avaliação <% else %> Avaliações</p><% end %>
    <% if @item.reviews.exists? %>
    <% @yes = (@item.reviews.where(buyagain: 1).count * 100.0 / @item.reviews.count).round(0) %>
    <% @no = (@item.reviews.where(buyagain: 0).count * 100.0 / @item.reviews.count).round(0) %>
    <% if @yes >= @no %>
      <div class="d-flex align-items-center mt-3 ml-4">
       <span class="likeitem fonthumb"><i class="far fa-thumbs-up"><%= @yes %>%</i></span><p class="flex-nowrap mt-4">Comprariam novamente</p>
      </div>
    <% else %>
      <div class="d-flex align-items-center">
       <span class="dislikeitem fonthumb"><i class="far fa-thumbs-down"><%= @no %>%</i></span><p class="flex-nowrap mt-3">Não comprariam novamente</p>
      </div>
    <% end %>
    <% end %>
    <br><%=    link_to 'Quero avaliar esse produto', new_item_review_path(@item.id), class: "btn btn-cadastrar mt-1 ml-5 mb-3" %>
    <% end %>
</div>